import { Country } from '@/lib/firestore/geography';

const createCountry = (name: string, isoCode: string, phoneCode: string, currency = ''): Country => ({
  id: `fallback-${isoCode.toLowerCase()}`,
  name,
  isoCode,
  phoneCode,
  currency,
  status: 'active',
});

export const FALLBACK_COUNTRIES: Country[] = [
  createCountry('Afghanistan', 'AF', '+93'),
  createCountry('Albania', 'AL', '+355'),
  createCountry('Algeria', 'DZ', '+213'),
  createCountry('Andorra', 'AD', '+376'),
  createCountry('Angola', 'AO', '+244'),
  createCountry('Antigua and Barbuda', 'AG', '+1'),
  createCountry('Argentina', 'AR', '+54'),
  createCountry('Armenia', 'AM', '+374'),
  createCountry('Australia', 'AU', '+61'),
  createCountry('Austria', 'AT', '+43'),
  createCountry('Azerbaijan', 'AZ', '+994'),
  createCountry('Bahamas', 'BS', '+1'),
  createCountry('Bahrain', 'BH', '+973'),
  createCountry('Bangladesh', 'BD', '+880'),
  createCountry('Barbados', 'BB', '+1'),
  createCountry('Belarus', 'BY', '+375'),
  createCountry('Belgium', 'BE', '+32'),
  createCountry('Belize', 'BZ', '+501'),
  createCountry('Benin', 'BJ', '+229'),
  createCountry('Bhutan', 'BT', '+975'),
  createCountry('Bolivia', 'BO', '+591'),
  createCountry('Bosnia and Herzegovina', 'BA', '+387'),
  createCountry('Botswana', 'BW', '+267'),
  createCountry('Brazil', 'BR', '+55'),
  createCountry('Brunei', 'BN', '+673'),
  createCountry('Bulgaria', 'BG', '+359'),
  createCountry('Burkina Faso', 'BF', '+226'),
  createCountry('Burundi', 'BI', '+257'),
  createCountry('Cambodia', 'KH', '+855'),
  createCountry('Cameroon', 'CM', '+237'),
  createCountry('Canada', 'CA', '+1'),
  createCountry('Cape Verde', 'CV', '+238'),
  createCountry('Central African Republic', 'CF', '+236'),
  createCountry('Chad', 'TD', '+235'),
  createCountry('Chile', 'CL', '+56'),
  createCountry('China', 'CN', '+86'),
  createCountry('Colombia', 'CO', '+57'),
  createCountry('Comoros', 'KM', '+269'),
  createCountry('Congo - Brazzaville', 'CG', '+242'),
  createCountry('Congo - Kinshasa', 'CD', '+243'),
  createCountry('Costa Rica', 'CR', '+506'),
  createCountry("Cote d'Ivoire", 'CI', '+225'),
  createCountry('Croatia', 'HR', '+385'),
  createCountry('Cuba', 'CU', '+53'),
  createCountry('Cyprus', 'CY', '+357'),
  createCountry('Czech Republic', 'CZ', '+420'),
  createCountry('Denmark', 'DK', '+45'),
  createCountry('Djibouti', 'DJ', '+253'),
  createCountry('Dominica', 'DM', '+1'),
  createCountry('Dominican Republic', 'DO', '+1'),
  createCountry('Ecuador', 'EC', '+593'),
  createCountry('Egypt', 'EG', '+20', 'EGP'),
  createCountry('El Salvador', 'SV', '+503'),
  createCountry('Equatorial Guinea', 'GQ', '+240'),
  createCountry('Eritrea', 'ER', '+291'),
  createCountry('Estonia', 'EE', '+372'),
  createCountry('Eswatini', 'SZ', '+268'),
  createCountry('Ethiopia', 'ET', '+251'),
  createCountry('Fiji', 'FJ', '+679'),
  createCountry('Finland', 'FI', '+358'),
  createCountry('France', 'FR', '+33'),
  createCountry('Gabon', 'GA', '+241'),
  createCountry('Gambia', 'GM', '+220'),
  createCountry('Georgia', 'GE', '+995'),
  createCountry('Germany', 'DE', '+49'),
  createCountry('Ghana', 'GH', '+233'),
  createCountry('Greece', 'GR', '+30'),
  createCountry('Grenada', 'GD', '+1'),
  createCountry('Guatemala', 'GT', '+502'),
  createCountry('Guinea', 'GN', '+224'),
  createCountry('Guinea-Bissau', 'GW', '+245'),
  createCountry('Guyana', 'GY', '+592'),
  createCountry('Haiti', 'HT', '+509'),
  createCountry('Honduras', 'HN', '+504'),
  createCountry('Hungary', 'HU', '+36'),
  createCountry('Iceland', 'IS', '+354'),
  createCountry('India', 'IN', '+91'),
  createCountry('Indonesia', 'ID', '+62'),
  createCountry('Iran', 'IR', '+98'),
  createCountry('Iraq', 'IQ', '+964'),
  createCountry('Ireland', 'IE', '+353'),
  createCountry('Israel', 'IL', '+972'),
  createCountry('Italy', 'IT', '+39'),
  createCountry('Jamaica', 'JM', '+1'),
  createCountry('Japan', 'JP', '+81'),
  createCountry('Jordan', 'JO', '+962'),
  createCountry('Kazakhstan', 'KZ', '+7'),
  createCountry('Kenya', 'KE', '+254'),
  createCountry('Kiribati', 'KI', '+686'),
  createCountry('Kuwait', 'KW', '+965'),
  createCountry('Kyrgyzstan', 'KG', '+996'),
  createCountry('Laos', 'LA', '+856'),
  createCountry('Latvia', 'LV', '+371'),
  createCountry('Lebanon', 'LB', '+961'),
  createCountry('Lesotho', 'LS', '+266'),
  createCountry('Liberia', 'LR', '+231'),
  createCountry('Libya', 'LY', '+218'),
  createCountry('Liechtenstein', 'LI', '+423'),
  createCountry('Lithuania', 'LT', '+370'),
  createCountry('Luxembourg', 'LU', '+352'),
  createCountry('Madagascar', 'MG', '+261'),
  createCountry('Malawi', 'MW', '+265'),
  createCountry('Malaysia', 'MY', '+60'),
  createCountry('Maldives', 'MV', '+960'),
  createCountry('Mali', 'ML', '+223'),
  createCountry('Malta', 'MT', '+356'),
  createCountry('Marshall Islands', 'MH', '+692'),
  createCountry('Mauritania', 'MR', '+222'),
  createCountry('Mauritius', 'MU', '+230'),
  createCountry('Mexico', 'MX', '+52'),
  createCountry('Micronesia', 'FM', '+691'),
  createCountry('Moldova', 'MD', '+373'),
  createCountry('Monaco', 'MC', '+377'),
  createCountry('Mongolia', 'MN', '+976'),
  createCountry('Montenegro', 'ME', '+382'),
  createCountry('Morocco', 'MA', '+212'),
  createCountry('Mozambique', 'MZ', '+258'),
  createCountry('Myanmar', 'MM', '+95'),
  createCountry('Namibia', 'NA', '+264'),
  createCountry('Nauru', 'NR', '+674'),
  createCountry('Nepal', 'NP', '+977'),
  createCountry('Netherlands', 'NL', '+31'),
  createCountry('New Zealand', 'NZ', '+64'),
  createCountry('Nicaragua', 'NI', '+505'),
  createCountry('Niger', 'NE', '+227'),
  createCountry('Nigeria', 'NG', '+234'),
  createCountry('North Korea', 'KP', '+850'),
  createCountry('North Macedonia', 'MK', '+389'),
  createCountry('Norway', 'NO', '+47'),
  createCountry('Oman', 'OM', '+968'),
  createCountry('Pakistan', 'PK', '+92'),
  createCountry('Palau', 'PW', '+680'),
  createCountry('Palestine', 'PS', '+970'),
  createCountry('Panama', 'PA', '+507'),
  createCountry('Papua New Guinea', 'PG', '+675'),
  createCountry('Paraguay', 'PY', '+595'),
  createCountry('Peru', 'PE', '+51'),
  createCountry('Philippines', 'PH', '+63'),
  createCountry('Poland', 'PL', '+48'),
  createCountry('Portugal', 'PT', '+351'),
  createCountry('Qatar', 'QA', '+974'),
  createCountry('Romania', 'RO', '+40'),
  createCountry('Russia', 'RU', '+7'),
  createCountry('Rwanda', 'RW', '+250'),
  createCountry('Saint Kitts and Nevis', 'KN', '+1'),
  createCountry('Saint Lucia', 'LC', '+1'),
  createCountry('Saint Vincent and the Grenadines', 'VC', '+1'),
  createCountry('Samoa', 'WS', '+685'),
  createCountry('San Marino', 'SM', '+378'),
  createCountry('Sao Tome and Principe', 'ST', '+239'),
  createCountry('Saudi Arabia', 'SA', '+966'),
  createCountry('Senegal', 'SN', '+221'),
  createCountry('Serbia', 'RS', '+381'),
  createCountry('Seychelles', 'SC', '+248'),
  createCountry('Sierra Leone', 'SL', '+232'),
  createCountry('Singapore', 'SG', '+65'),
  createCountry('Slovakia', 'SK', '+421'),
  createCountry('Slovenia', 'SI', '+386'),
  createCountry('Solomon Islands', 'SB', '+677'),
  createCountry('Somalia', 'SO', '+252'),
  createCountry('South Africa', 'ZA', '+27'),
  createCountry('South Korea', 'KR', '+82'),
  createCountry('South Sudan', 'SS', '+211'),
  createCountry('Spain', 'ES', '+34'),
  createCountry('Sri Lanka', 'LK', '+94'),
  createCountry('Sudan', 'SD', '+249'),
  createCountry('Suriname', 'SR', '+597'),
  createCountry('Sweden', 'SE', '+46'),
  createCountry('Switzerland', 'CH', '+41'),
  createCountry('Syria', 'SY', '+963'),
  createCountry('Taiwan', 'TW', '+886'),
  createCountry('Tajikistan', 'TJ', '+992'),
  createCountry('Tanzania', 'TZ', '+255'),
  createCountry('Thailand', 'TH', '+66'),
  createCountry('Timor-Leste', 'TL', '+670'),
  createCountry('Togo', 'TG', '+228'),
  createCountry('Tonga', 'TO', '+676'),
  createCountry('Trinidad and Tobago', 'TT', '+1'),
  createCountry('Tunisia', 'TN', '+216'),
  createCountry('Turkey', 'TR', '+90'),
  createCountry('Turkmenistan', 'TM', '+993'),
  createCountry('Tuvalu', 'TV', '+688'),
  createCountry('Uganda', 'UG', '+256'),
  createCountry('Ukraine', 'UA', '+380'),
  createCountry('United Arab Emirates', 'AE', '+971'),
  createCountry('United Kingdom', 'GB', '+44'),
  createCountry('United States', 'US', '+1'),
  createCountry('Uruguay', 'UY', '+598'),
  createCountry('Uzbekistan', 'UZ', '+998'),
  createCountry('Vanuatu', 'VU', '+678'),
  createCountry('Vatican City', 'VA', '+379'),
  createCountry('Venezuela', 'VE', '+58'),
  createCountry('Vietnam', 'VN', '+84'),
  createCountry('Yemen', 'YE', '+967'),
  createCountry('Zambia', 'ZM', '+260'),
  createCountry('Zimbabwe', 'ZW', '+263'),
].sort((a, b) => a.name.localeCompare(b.name));
